'use-strict';

const ROUTE_PATHS = {
    ROOT:"/",
    BASE:"/V3",
    TEST_API:"/test-api",
    WALLET:"/wallet",
    SELF:"/self",
    PLUS:"/plus",

    ADD:"/add",
    DETAIL:"/detail",
    LIST:"/list"
}

exports.ROUTE_PATHS = ROUTE_PATHS;

const ROUTE_PARAMS = {
    USERID:"/:userid",
    NAMESPACE:"/:namespace",
    LEVEL:"/:level",
    RESOURCE:"/:resource",
    VERSION : "/V:VERSION",
    ACTION : "/:action"
}

exports.ROUTE_PARAMS = ROUTE_PARAMS;

exports.RET_CODE = {
  OK: 1000,
  FAILURE: 1001,

  DUPLICATED: 2002,
  TOKEN_EXPIRED: 2003,
  INCORRECT_HANDLE: 2004,
  NONEXISTENT_HANDLE: 2005,
  INCORRECT_PASSWORD: 2006,
  INCORRECT_CAPTCHA: 2007,
  INVALID_EMAIL_LITERAL: 2008,
  NO_ASSOCIATED_EMAIL: 2009,
  SEND_EMAIL_TIMEOUT: 2010,

  INCORRECT_PHONE_COUNTRY_CODE_OR_NUMBER: 2011,

  INVALID_KIOSK_CREDENTIALS: 3000,
  INSUFFICIENT_MEM_TO_ALLOCATE_CONNECTION: 3001,
  KIOSK_ALREADY_CONNECTED: 3002,
  NONEXISTENT_KIOSK: 3003,

  PASSWORD_RESET_CODE_GENERATION_PER_EMAIL_TOO_FREQUENTLY: 4000,
  CAPTCHA_GENERATION_PER_PHONE_TOO_FREQUENTLY: 4001,
  TRADE_CREATION_TOO_FREQUENTLY: 4002,

  NOT_IMPLEMENTED_YET: 65535,
};

